### ISSUE TITLE
Delay Threshold

### ISSUE THREAD

**Issue by mpiraux** [obonaventure/draft-schedulers#13]
I sketched some code and Matthieu provided a description but I am unsure that both match the scheduler we intended to describe while reading Olivier's comment:

> OB: Path 0 has a higher priority than path one, path one is used if packets has been delayed by more than threshold in transport entity

Currently, packets are injected on path 1 if path 0 has a higher RTT than the threshold AND if path 0 is blocked. I wonder whether that AND condition is correct. The comment could be read as follows:

Send packets on path 0 if not blocked. If a packet cannot be scheduled on path 0 for a larger amount of time than the threshold, send it over path 1. There is no way to get the current time in the scheduler.

Let's keep it that way for -00 and fix it in -01.

**Comment by matttbe** [comment]
I indeed added a description fitting with the code, not Olivier's comment.

The idea of Olivier can be useful to give less priority to one link. But I don't know if it can be applied often: if we are limited by the receiver, packets can wait for a "long time" in the different queues and then this technique doesn't help.

**Comment by matttbe** [comment]
Maybe for the -00, we can at least replace the title: Delay Threshold → RTT threshold?

**Comment by matttbe** [comment]
It seems RTT and Delay can point to the same concept. So I guess it is fine not to change the title.

**Comment by mpiraux** [comment]
I would like to incorporate the recent and upcoming changes in a -01 version. I suppose the conclusion of this discussion is to close the issue with no action, right ?

**Comment by matttbe** [comment]
@mpiraux maybe we want to change the title? To be checked with @obonaventure if he agrees with the version that was written and the title as it doesn't seem to match with the comment.

**Comment by obonaventure** [comment]
rtt threshold is fine for me
